name: When using the workflow_run event
run-name: Workflow run by Other Workflow run

on:
  workflow_run:
    workflows: ["Github Issue"]
    types: [requested]
    branches:
      - 'releases/**'

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Other workflow is running
        run: |
          echo "success"
