name: Github Issue
run-name: Workflow run by issue create

on:
  workflow_run:
    workflows: ["Github Issue"]
    types: [requested]
    branches:
      - 'releases/**'

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "success"
